heat_template_version: 2015-04-30
description: Deployment of MariaDB-Galera CLuster with 3 nodes (Primary and Standby) 

parameters:

  image_id:
    type: string
    description: Image used for servers
    default: ubuntu-xenial-16.04_lastest
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
    default: gp1.small
  availability_zone:
    type: string
    description: Availability Zone of the nodes.
    default: zone00
  resource_name:
    type: string
    description: Name-prefix for created resources in OpenStack.

  primary_volume_id:
    type: string
    description: ID of the pre-created volume to be attached to the primary node.
  primary_port:
    type: string
    description: Port-ID of the pre-created Port for the primary node.
  primary_ip:
    type: string
    description: IP of primary node.

  secondary1_volume_id:
    type: string
    description: ID of the pre-created volume to be attached to the secondary node 1.
  secondary1_port:
    type: string
    description: Network-Port used by the standby node.
  secondary1_ip:
    type: string
    description: IP of  secondary node 1.

  secondary2_volume_id:
    type: string
    description: ID of the pre-created volume to be attached to the secondary node 2.
  secondary2_port:
    type: string
    description: Network-Port used by the standby node.
  secondary2_ip:
    type: string
    description: IP of  secondary node 2.


  service_db:
    type: string
    description: Name of the Database.
    default: servicedb
  admin_user:
    type: string
    description: Admin user for the service.
    default: servicedb
  admin_password:
    type: string
    hidden: true
    description: Password for the service_user password.
    

resources:

  maria_prim_server:
    type: primary.yaml
    properties:
      primary_hostname:
        str_replace:
          template: $hostname-n0
          params:
            $hostname: { get_param: resource_name }
      image_id: {get_param: image_id }
      key_name: {get_param: key_name }
      flavor: {get_param: flavor }
      availability_zone: {get_param: availability_zone }
      service_db: {get_param: service_db }
      admin_user: {get_param: admin_user }
      admin_password: {get_param: admin_password }
      primary_port: {get_param: primary_port }
      primary_ip: {get_param: primary_ip }
      primary_volume_id: {get_param: primary_volume_id }
      secondaries_ip_list:
        str_replace:
          template: $sec1,$sec2
          params:
            $sec1: {get_param: secondary1_ip }
            $sec2: {get_param: secondary2_ip }


  maria_sec1_server:
    type: secondaries.yaml
    depends_on: maria_prim_server
    properties:
      secondary_hostname:
        str_replace:
          template: $hostname-n1
          params:
            $hostname: { get_param: resource_name }
      image_id: {get_param: image_id }
      key_name: {get_param: key_name }
      flavor: {get_param: flavor }
      availability_zone: {get_param: availability_zone }
      service_db: {get_param: service_db }
      admin_user: {get_param: admin_user }
      admin_password: {get_param: admin_password }
      secondary_port: {get_param: secondary1_port }
      primary_ip: {get_param: primary_ip }
      secondary_volume_id: {get_param: secondary1_volume_id }
      secondary_ip: {get_param: secondary1_ip }
      secondaries_ip_list:
        str_replace:
          template: $sec1,$sec2
          params:
            $sec1: {get_param: secondary1_ip }
            $sec2: {get_param: secondary2_ip }



  maria_sec2_server:
    type: secondaries.yaml
    depends_on: maria_prim_server
    properties:
      secondary_hostname:
        str_replace:
          template: $hostname-n2
          params:
            $hostname: { get_param: resource_name }
      image_id: {get_param: image_id }
      key_name: {get_param: key_name }
      flavor: {get_param: flavor }
      availability_zone: {get_param: availability_zone }
      service_db: {get_param: service_db }
      admin_user: {get_param: admin_user }
      admin_password: {get_param: admin_password }
      secondary_port: {get_param: secondary2_port }
      primary_ip: {get_param: primary_ip }
      secondary_volume_id: {get_param: secondary2_volume_id }
      secondary_ip: {get_param: secondary2_ip }
      secondaries_ip_list:
        str_replace:
          template: $sec1,$sec2
          params:
            $sec1: {get_param: secondary1_ip }
            $sec2: {get_param: secondary2_ip }